
package cn.live.ws.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import cn.live.ws.service.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MyService", targetNamespace = "http://service.ws.live.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reverse", targetNamespace = "http://service.ws.live.cn/", className = "cn.live.ws.service.Reverse")
    @ResponseWrapper(localName = "reverseResponse", targetNamespace = "http://service.ws.live.cn/", className = "cn.live.ws.service.ReverseResponse")
    public String reverse(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
